name: workflow to run python program
on:
  push:
    branches:
      - main

jobs:
  extract_transform_data:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: show python version
      run: python --version  
    - name: use python specific version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: show version
      run: python --version    
    - name: dependencies  
      run: pip install -r requirments.txt
    - name: run extract_data.py
      run: python extract_data.py 
