name: workflow to run python program
on:
  push:
    branches:
      - main

jobs:
  extract_transform_data:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install dependencies
      run: pip install -r requirments.txt  
    - name: run extract_data.py
      run: python extract_data.py
